# Site settings
title: Christophe's blog
email: 4630125+christ-off@users.noreply.github.com
description: My blog about dev mainly Java and Spring
url: https://christ-off.github.io
author: christ-off

# Social icons
github_username: Christ-OFF

exclude: [ "etc", "README.md" , "vendor"]
# include:

# Build settings
permalink: :title/
sass:
  sass_dir: css
