# Site settings
title: Christophe's blog
email: 4630125+christ-off@users.noreply.github.com
description: My blog about dev mainly Java and Spring
url: https://christ-off.github.io
author: christ-off

# Social icons
show_social_icons: true
github_username: Christ-OFF
mastodon_profile: https://diaspodon.fr/@Christ_OFF_
twitter_username: PostTenebrasDev

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 4

defaults:
  - scope:
      path:            "404.html"
    values:
      sitemap:         false
  - scope:
      path:            "googlef4eb191109cf8ea9.html"
    values:
      sitemap:         false
  - scope:
      path:            "BingSiteAuth.xml"
    values:
      sitemap:         false

# Build settings
permalink: :title/
sass:
  sass_dir: css

#Exclude
exclude: [".idea"]
